name: Java Build and Artifact

on:
  push: {branches: ["master", "main"]}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/VanillaSMP-1.0.jar
